### ISSUE TITLE
Release minesweeper 1.0.0

### ISSUE THREAD

**Issue by hrryt** [hrryt/minesweeper#1]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [x] `usethis::use_news_md()`

**Comment by Maarten14C** [comment]
I'm having trouble playing this on a Mac - it can only play upon opening an x11() window. I suggest adding checks for which displays are available.

Using a trackpad, I can place flags on any of the tiles, but none of the other functions seem to work.

**Comment by hrryt** [comment]
Hi Maarten,
`play_minesweeper()` errors intentionally if the current device does not support event handling; see `?play_minesweeper`. Devices that support event handling include `windows()`, `X11(type = "Xlib")` and `X11(type = "cairo")` (see `?getGraphicsEvent`), which explains why it worked upon opening an `x11()` window. Perhaps I should make this clearer in the documentation.

I have played this using a trackpad with no issues, so I'm not sure how to help in that regard. Flagging is the only function that uses the right mouse button rather than the left, if that helps.

**Comment by hrryt** [comment]
Hi Maarten, thanks for your contribution. Should work on Mac now.
